### ISSUE TITLE
Suggestion: Package template files into code

### ISSUE THREAD

**Issue by craigmc08** [albe-rosado/create-proton-app#1]
Instead of copying files from the template dir, save index.js and .babelrc somewhere else. I'm suggesting this so that you can run `npx create-proton-app [app-name]`, which is a convenient feature that comes with the latest version of npm. npx command will temporarily install packages and run them, instead of having to install packages like this globally.

**Comment by albe-rosado** [comment]
I have thought about creating a `proton-scripts` kind of package that could be installed via `npm` instead of copying from the template folder. But yeah, this weekend I will give it a try, `npx` compatibility is definitely in my immediate future plan. If you want to submit a PR for that would be awesome, anyways thanks a lot @craigmc08

**Comment by albe-rosado** [comment]
thanks, @craigmc08 , I just merged your changes. I don't use windows since XP, so in the future, if you note something that could screw Windows compatibility, please, tell me, thanks a lot.
